# Generated by Django 5.0.6 on 2024-07-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_bus_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='line',
        ),
        migrations.AddField(
            model_name='bus',
            name='lines',
            field=models.ManyToManyField(related_name='buses', to='base.line'),
        ),
    ]
