# Generated by Django 5.0.6 on 2024-07-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_bus_line_bus_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='lines',
            field=models.ManyToManyField(to='base.line'),
        ),
    ]
