# Generated by Django 3.2.12 on 2024-06-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_id', models.CharField(db_index=True, max_length=12, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
            ],
        ),
    ]
