# Generated by Django 3.2.12 on 2024-06-20 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(db_index=True, max_length=3, unique=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(db_index=True, max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OrdinATAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.line')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('latitude', models.FloatField(max_length=10)),
                ('longitude', models.FloatField(max_length=10)),
                ('lines', models.ManyToManyField(through='base.OrdinATAC', to='base.Line')),
            ],
        ),
        migrations.AddField(
            model_name='ordinatac',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stop'),
        ),
        migrations.AddField(
            model_name='line',
            name='stops',
            field=models.ManyToManyField(through='base.OrdinATAC', to='base.Stop'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(db_index=True, max_length=12, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('assingned_bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bus')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.line'),
        ),
        migrations.AddField(
            model_name='bus',
            name='passengers',
            field=models.ManyToManyField(to='base.Passenger'),
        ),
    ]
